tap "hashicorp/tap"

tap "oven-sh/bun"
brew "bash"
brew "gh"
brew "go"
brew "shellcheck"
brew "shfmt"
brew "tcptraceroute"
brew "wget"
brew "hashicorp/tap/terraform"
brew "oven-sh/bun/bun"
cask "orbstack"
